source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Sample1128' do
  use_frameworks!
  pod 'SwiftDate', '~> 4.4.2'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'master'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'master'
#  pod 'ReactorKit'
#  pod 'SnapKit', '~> 4.0.0'
#  pod 'R.swift', '~> 5.1.0'
#  pod 'Hero'
#  pod 'Then', '~> 2.6'
   pod 'lottie-ios'



end
