source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

target 'Sample1128' do
  use_frameworks!
  pod 'RxCocoa'
  pod 'RxSwift'
end
