source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Sample1128' do
  use_frameworks!
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'lottie-ios'

#  pod 'PAYJP'
#  pod 'ReactorKit'
#  pod 'SnapKit', '~> 4.0.0'
#  pod 'R.swift', '~> 5.1.0'
#  pod 'Hero'
#  pod 'Then', '~> 2.6'



end
