name: Sample1128
options:
  bundleIdPrefix: jp.donovan.Sample1128
targets:
  Sample1128:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: 
      - path: Sample1128
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
      SWIFT_VERSION: 5.0
    dependencies:
      - carthage: RxSwift　
