name: Sample1128
options:
  bundleIdPrefix: jp.donovan
targets:
  Sample1128:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: 
      - path: Sample1128
    settings:
      
      configs:
        debug:
          IPHONEOS_DEPLOYMENT_TARGET: 10.
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          IPHONEOS_DEPLOYMENT_TARGET: 10.0
          CUSTOM_BUILD_SETTING: my_release_value        
      SWIFT_VERSION: 5.0
    dependencies:
      - carthage: RxSwift


