name: NSApp
options:
  bundleIdPrefix: jp.neurospace.leeJet.dev
targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: 
      - path: NSApp
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
      SWIFT_VERSION: 5.0
    dependencies:
      - carthage: RxSwift　
