//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** ポイント残高照会要求を行います。
 <B>制約</B>
 ・特になし
 <details>
 <summary>変更履歴</summary>
 2020.5.7 モールAPI化 新規作成
 2020.5.28 モールAPI化 HTTPステータスコード400に記載していたapigeeからのエラーコードについては、別紙を参照するように記載を変更
 2020.06.04 TWサーバ処理にてレスポンスコード400を返却する場合があるため、レスポンスに追加</details> */
// sourcery: AutoInit
struct GetMallPointRest {
    /** キャッシュバック申請受付中フラグ */
    var cbFlg: String?
    /** キャッシュバック金額1 */
    var cbKingaku1: Int?
    /** キャッシュバック金額2 */
    var cbKingaku2: Int?
    /** キャッシュバック金額3 */
    var cbKingaku3: Int?
    /** キャッシュバック金額4 */
    var cbKingaku4: Int?
    /** キャッシュバック金額5 */
    var cbKingaku5: Int?
    /** カード会員番号下4桁 */
    var crdKaiinNo4f: String?
    /** カード管理番号 */
    var crdKnrNo: String?
    /** 会員NO */
    var kaiinNo: String?
    /** 期間限定ポイント合計 */
    var kikanPtKei: Int?
    /** 期間限定ポイント残高(フリー) */
    var kikanZndkFree: Int?
    /** 期間限定ポイント残高(限定) */
    var kikanZndkLtd: Int?
    /** 期間限定ポイント残高(全加盟店限定) */
    var kikanZndkLtdAll: Int?
    /** 加盟店期間限定ポイント合計 */
    var kmtKikanPtKei: Int?
    /** 加盟店総保有ポイント */
    var kmtSouHoyuPt: Int?
    /** 交換可能ポイント */
    var koukanKanoPt: Int?
    /** メッセージ(結果コードに紐付くメッセージ) */
    var message: String?
    /** ポイント有効区分 */
    var ptYukoKbn: String?
    /** 通常ポイント有効期間(MM) */
    var ptYukoKikan: Int?
    /** 結果コード */
    var result: String?
    /** モールカードサービス業務制御(還元) */
    var seiflgKng: String?
    /** モールカードサービス業務制御(照会) */
    var seiflgSyk: String?
    /** 総保有ポイント */
    var souHoyuPt: Int?
    /** 商品ID1 */
    var syohinId1: String?
    /** 商品ID2 */
    var syohinId2: String?
    /** 商品ID3 */
    var syohinId3: String?
    /** 商品ID4 */
    var syohinId4: String?
    /** 商品ID5 */
    var syohinId5: String?
    /** TMCスクランブルTopS管理ナンバー */
    var tmcScrambleTopsKanriNo: String?
    /** TopS管理ナンバー */
    var topsKanriNo: String?
    /** 通貨ID */
    var tukaId: String?
    /** 直近失効予定日 */
    var tyokinSikkoYoteiBi: String?
    /** 直近失効予定ポイント */
    var tyokinSikkoYoteiPt: Int?
    /** 付与予定期間限定ポイント残高 */
    var yoteiKikanZndk: Int?
    /** 通常ポイント残高 */
    var zndk: Int?
    /** 残高ゼロ表示フラグ */
    var zndkZeroFlg: String?

    // sourcery:inline:auto:GetMallPointRest.AutoInit
    // swiftlint:disable all
    // swiftformat:disable all
    internal init(cbFlg: String? = nil, cbKingaku1: Int? = nil, cbKingaku2: Int? = nil, cbKingaku3: Int? = nil, cbKingaku4: Int? = nil, cbKingaku5: Int? = nil, crdKaiinNo4f: String? = nil, crdKnrNo: String? = nil, kaiinNo: String? = nil, kikanPtKei: Int? = nil, kikanZndkFree: Int? = nil, kikanZndkLtd: Int? = nil, kikanZndkLtdAll: Int? = nil, kmtKikanPtKei: Int? = nil, kmtSouHoyuPt: Int? = nil, koukanKanoPt: Int? = nil, message: String? = nil, ptYukoKbn: String? = nil, ptYukoKikan: Int? = nil, result: String? = nil, seiflgKng: String? = nil, seiflgSyk: String? = nil, souHoyuPt: Int? = nil, syohinId1: String? = nil, syohinId2: String? = nil, syohinId3: String? = nil, syohinId4: String? = nil, syohinId5: String? = nil, tmcScrambleTopsKanriNo: String? = nil, topsKanriNo: String? = nil, tukaId: String? = nil, tyokinSikkoYoteiBi: String? = nil, tyokinSikkoYoteiPt: Int? = nil, yoteiKikanZndk: Int? = nil, zndk: Int? = nil, zndkZeroFlg: String? = nil) {
        self.cbFlg = cbFlg
        self.cbKingaku1 = cbKingaku1
        self.cbKingaku2 = cbKingaku2
        self.cbKingaku3 = cbKingaku3
        self.cbKingaku4 = cbKingaku4
        self.cbKingaku5 = cbKingaku5
        self.crdKaiinNo4f = crdKaiinNo4f
        self.crdKnrNo = crdKnrNo
        self.kaiinNo = kaiinNo
        self.kikanPtKei = kikanPtKei
        self.kikanZndkFree = kikanZndkFree
        self.kikanZndkLtd = kikanZndkLtd
        self.kikanZndkLtdAll = kikanZndkLtdAll
        self.kmtKikanPtKei = kmtKikanPtKei
        self.kmtSouHoyuPt = kmtSouHoyuPt
        self.koukanKanoPt = koukanKanoPt
        self.message = message
        self.ptYukoKbn = ptYukoKbn
        self.ptYukoKikan = ptYukoKikan
        self.result = result
        self.seiflgKng = seiflgKng
        self.seiflgSyk = seiflgSyk
        self.souHoyuPt = souHoyuPt
        self.syohinId1 = syohinId1
        self.syohinId2 = syohinId2
        self.syohinId3 = syohinId3
        self.syohinId4 = syohinId4
        self.syohinId5 = syohinId5
        self.tmcScrambleTopsKanriNo = tmcScrambleTopsKanriNo
        self.topsKanriNo = topsKanriNo
        self.tukaId = tukaId
        self.tyokinSikkoYoteiBi = tyokinSikkoYoteiBi
        self.tyokinSikkoYoteiPt = tyokinSikkoYoteiPt
        self.yoteiKikanZndk = yoteiKikanZndk
        self.zndk = zndk
        self.zndkZeroFlg = zndkZeroFlg
    }
    // sourcery:end
}
