//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** ポイント履歴内訳照会要求を行います。
 <B>制約</B>
 ・特になし
 <details>
 <summary>変更履歴</summary>
 2020.5.12 モールAPI化 新規作成
 2020.5.28 モールAPI化 HTTPステータスコード400に記載していたapigeeからのエラーコードについては、別紙を参照するように記載を変更
 2020.06.04 TWサーバ処理にてレスポンスコード400を返却する場合があるため、レスポンスに追加</details> */
// sourcery: AutoInit
struct GetMallPointHistory {
    /** 総件数 */
    var kensu: Int?
    /** メッセージ(結果コードに紐付くメッセージ) */
    var message: String?
    /** 獲得年月 */
    var nengetu: String?
    /** ポイント履歴内訳 */
    var ptRirekiUchiwake: [PtRirekiUchiwake]?
    /** 結果コード */
    var result: String?

    struct PtRirekiUchiwake {
        /** 取消可能フラグ */
        var cancelKanoFlg: String?
        /** 代表加盟店名称 */
        var daihyoKmtName: String?
        /** 付与理由 */
        var fuyoRiyu: String?
        /** 事由コード */
        var jiyuCd: String?
        /** 事由詳細コード */
        var jiyuDetCd: String?
        /** ポイント数 */
        var pt: Int?
        /** 取引日付 */
        var torihikiBi: String?
        /** 取引種類 */
        var torihikiType: String?
        /** 売上No */
        var uriageNo: String?
    }

    // sourcery:inline:auto:GetMallPointHistory.AutoInit
    // swiftlint:disable all
    // swiftformat:disable all
    internal init(kensu: Int? = nil, message: String? = nil, nengetu: String? = nil, ptRirekiUchiwake: [PtRirekiUchiwake]? = nil, result: String? = nil) {
        self.kensu = kensu
        self.message = message
        self.nengetu = nengetu
        self.ptRirekiUchiwake = ptRirekiUchiwake
        self.result = result
    }
    // sourcery:end
}
