//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** TSPay紐付照会要求を行います。
 <B>制約</B>
 ・特になし
 <details>
 <summary>変更履歴</summary>
 2020.5.15 モールAPI化 新規作成
 2020.5.28 モールAPI化 HTTPステータスコード400に記載していたapigeeからのエラーコードについては、別紙を参照するように記載を変更
 2020.06.04 TWサーバ処理にてレスポンスコード400を返却する場合があるため、レスポンスに追加</details> */
// sourcery: AutoInit
struct GetTspayLinks {
    /** B01データ部情報 */
    var b01: B01?
    /** B02データ部情報 */
    var b02: [B02]?
    /** メッセージ(結果コードに紐付くメッセージ) */
    var message: String?
    /** 結果コード */
    var result: String?

    /** B01データ部情報 */
    struct B01 {
        /** カード枚数 */
        var cardCnt: String?
    }

    struct B02 {
        /** カードブランドコード */
        var crdBrndCd: String?
        /** ブランド名称 */
        var crdBrndName: String?
        /** カード会社コード */
        var crdCoCd: String?
        /** カード会員番号 下4桁 */
        var crdKainNo4f: String?
        /** カード管理番号 */
        var crdKnrNo: String?
        /** カード名称 */
        var crdName: String?
        /** カード種類コード */
        var crdShrCd: String?
        /** カード種類名称 */
        var crdShrName: String?
        /** カード提携会社コード1 */
        var crdTkCoCd1: String?
        /** カード提携会社コード2 */
        var crdTkCoCd2: String?
        /** カード提携方式コード */
        var crdTkHshCd: String?
    }

    // sourcery:inline:auto:GetTspayLinks.AutoInit
    // swiftlint:disable all
    // swiftformat:disable all
    internal init(b01: B01? = nil, b02: [B02]? = nil, message: String? = nil, result: String? = nil) {
        self.b01 = b01
        self.b02 = b02
        self.message = message
        self.result = result
    }
    // sourcery:end
}
